# Generated by Django 6.0.2 on 2026-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('type_customer', models.CharField(max_length=100)),
                ('nomina_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('credit_line', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('mora_days', models.IntegerField()),
                ('score', models.CharField(max_length=10)),
            ],
        ),
    ]
