# Generated by Django 6.0.2 on 2026-06-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='num_obligacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
