# Generated by Django 6.0.2 on 2026-07-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_line',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mora_days',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='num_obligacion',
        ),
        migrations.CreateModel(
            name='Obligations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_obligacion', models.IntegerField()),
                ('credit_line', models.CharField(max_length=100)),
                ('mora_days', models.IntegerField()),
                ('total', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='customers.customer')),
            ],
        ),
    ]
