# Generated by Django 6.0.2 on 2026-07-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_credit_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligations',
            name='num_obligacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
