# Generated by Django 6.0.2 on 2026-07-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customerlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlog',
            name='message',
        ),
        migrations.AddField(
            model_name='customerlog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='action',
            field=models.CharField(choices=[('customer_created', 'Asociado creado'), ('customer_updated', 'Asociado actualizado'), ('obligation_created', 'Obligación creada'), ('obligation_updated', 'Obligación actualizada')], max_length=50),
        ),
    ]
