# Generated by Django 6.0.2 on 2026-07-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customerlog_message_customerlog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
