# Generated by Django 6.0.2 on 2026-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contributions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
