# Generated by Django 6.0.2 on 2026-09-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_age_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importexecution',
            options={'permissions': [('import_importexecution', 'Puede importar obligaciones')]},
        ),
    ]
