# Generated by Django 6.0.2 on 2026-06-02 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('hour', models.IntegerField(choices=[(8, '08:00 AM'), (9, '09:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '01:00 PM'), (14, '02:00 PM'), (15, '03:00 PM'), (16, '04:00 PM'), (17, '05:00 PM')])),
                ('days_of_week', models.JSONField(default=list)),
                ('action', models.CharField(choices=[('send_email', 'Enviar correo')], max_length=50)),
                ('filters', models.JSONField(default=list)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('mora_days', 'Días Mora'), ('age', 'Edad'), ('gender', 'Género'), ('city', 'Ciudad'), ('score', 'Score')], max_length=50)),
                ('operator', models.CharField(choices=[('eq', 'Igual'), ('neq', 'Diferente'), ('gt', 'Mayor'), ('gte', 'Mayor o igual'), ('lt', 'Menor'), ('lte', 'Menor o igual'), ('between', 'Entre'), ('in', 'En lista'), ('contains', 'Contiene')], max_length=20)),
                ('value', models.JSONField()),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters_auto', to='automations.automation')),
            ],
        ),
    ]
