# Generated by Django 6.0.2 on 2026-06-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='filters',
        ),
        migrations.AddField(
            model_name='automationfilter',
            name='range_from',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='automationfilter',
            name='range_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='automationfilter',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
