# Generated by Django 6.0.2 on 2026-06-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_remove_automation_filters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationfilter',
            name='operator',
            field=models.CharField(choices=[('eq', 'Igual'), ('gte', 'Mayor o igual'), ('lte', 'Menor o igual'), ('between', 'Entre'), ('in', 'En lista')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automationfilter',
            name='range_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='automationfilter',
            name='range_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='automationfilter',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
