# Generated by Django 6.0.2 on 2026-06-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_alter_automationfilter_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationfilter',
            name='automation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filters_auto', to='automations.automation'),
        ),
    ]
