# Generated by Django 6.0.2 on 2026-06-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_alter_automationfilter_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='automations/'),
        ),
        migrations.AddField(
            model_name='automation',
            name='weeks_of_month',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='automationfilter',
            name='operator',
            field=models.CharField(choices=[('eq', 'Igual'), ('gte', 'Mayor o igual'), ('lt', 'Menor'), ('lte', 'Menor o igual'), ('between', 'Entre'), ('in', 'En lista')], max_length=20),
        ),
    ]
