# Generated by Django 6.0.2 on 2026-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_automation_image_automation_weeks_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AddField(
            model_name='automation',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
    ]
