# Generated by Django 6.0.2 on 2026-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0006_automation_date_from_automation_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='content_type',
            field=models.CharField(choices=[('html', 'HTML'), ('text', 'Texto plano')], default='html', max_length=10),
        ),
    ]
