# Generated by Django 6.0.2 on 2026-07-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_automation_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationfilter',
            name='field',
            field=models.CharField(choices=[('mora_days', 'Días Mora'), ('age', 'Edad'), ('gender', 'Género'), ('city', 'Ciudad'), ('score', 'Score'), ('status', 'Estado del asociado'), ('type_associate', 'Tipo de asociado')], max_length=50),
        ),
    ]
