# Generated by Django 6.0.2 on 2026-07-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0008_alter_automationfilter_field'),
        ('customers', '0008_remove_customerlog_message_customerlog_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('success', 'Enviado'), ('failed', 'Fallido')], max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_day', models.DateField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='customers.customer')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='customers.obligations')),
            ],
        ),
    ]
