# Generated by Django 6.0.2 on 2026-07-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0009_automationexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
