# Generated by Django 6.0.2 on 2026-07-18 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0010_automation_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationfilter',
            name='field',
            field=models.CharField(choices=[('mora_days', 'Días Mora'), ('age', 'Edad'), ('gender', 'Género'), ('city', 'Ciudad'), ('status', 'Estado del asociado'), ('type_associate', 'Tipo de asociado')], max_length=50),
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('enabled', 'Activada'), ('disabled', 'Desactivada'), ('executed', 'Ejecutada'), ('deleted', 'Eliminada')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='automations.automation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
