# Generated by Django 6.0.2 on 2026-08-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0011_alter_automationfilter_field_automationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationfilter',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='automations.automation'),
        ),
        migrations.AlterField(
            model_name='automationfilter',
            name='field',
            field=models.CharField(choices=[('mora_days', 'Días Mora'), ('age', 'Edad'), ('gender', 'Género'), ('city', 'Ciudad'), ('status', 'Estado del asociado'), ('type_associate', 'Tipo de asociado'), ('nomina_name', 'Nominas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='automationfilter',
            name='operator',
            field=models.CharField(choices=[('eq', 'Igual'), ('gte', 'Mayor o igual'), ('lt', 'Menor'), ('lte', 'Menor o igual'), ('between', 'Entre'), ('in', 'En lista'), ('diff', 'Diferente')], max_length=20),
        ),
    ]
