# Generated by Django 6.0.2 on 2026-09-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0012_alter_automationfilter_automation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automation',
            options={'permissions': [('execute_automation', 'Puede ejecutar automatizaciones'), ('test_automation', 'Puede probar automatizaciones')]},
        ),
    ]
